// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.CouponAPI.Data;

#nullable disable

namespace Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240501160100_CouponTables")]
    partial class CouponTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "03cccfa5-9a07-4348-a5d1-3f761bdf72b9",
                            DiscountAmount = 10.0,
                            LastUpdated = new DateTime(2024, 5, 1, 16, 0, 59, 886, DateTimeKind.Utc).AddTicks(6736),
                            MinAmount = 20000
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "447610f7-f890-404a-b466-c40c721fee7a",
                            DiscountAmount = 20.0,
                            LastUpdated = new DateTime(2024, 5, 1, 16, 0, 59, 886, DateTimeKind.Utc).AddTicks(6769),
                            MinAmount = 50000
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "34e84b78-a808-42a6-bcd8-6b434e6ec1a1",
                            DiscountAmount = 15.0,
                            LastUpdated = new DateTime(2024, 5, 1, 16, 0, 59, 886, DateTimeKind.Utc).AddTicks(6783),
                            MinAmount = 25000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
